# Generated by Django 3.1.2 on 2020-10-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('cam', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('time_zone', models.CharField(max_length=32)),
                ('url', models.URLField(max_length=1024)),
                ('description', models.CharField(max_length=64)),
            ],
        ),
    ]
