# Generated by Django 3.1 on 2020-08-18 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detector',
            fields=[
                ('detector_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('cam', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('time_zone', models.CharField(max_length=32)),
                ('url', models.URLField(max_length=1024)),
                ('description', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('detector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detector_log', to='traffic_monitor.detector')),
                ('feed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_log', to='traffic_monitor.feed')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('key', models.BigAutoField(primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField()),
                ('class_id', models.CharField(max_length=32)),
                ('count', models.FloatField(default=0)),
                ('monitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_log', to='traffic_monitor.monitor')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=64)),
                ('class_id', models.CharField(max_length=64)),
                ('is_monitoring', models.BooleanField(default=True)),
                ('is_logging', models.BooleanField(default=True)),
                ('monitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='traffic_monitor.monitor')),
            ],
        ),
    ]
