# Generated by Django 3.1 on 2020-08-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='log_objects',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='monitor',
            name='notification_objects',
            field=models.JSONField(default=[]),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
