# Generated by Django 3.0.6 on 2020-05-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='key',
            field=models.CharField(default=0, max_length=128, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(max_length=64),
        ),
    ]
