# Generated by Django 3.0.6 on 2020-05-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_monitor', '0002_auto_20200519_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_id',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
