# Generated by Django 3.1 on 2020-08-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_monitor', '0002_auto_20200820_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='log_objects',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='notification_objects',
            field=models.JSONField(default=list),
        ),
    ]
