# Generated by Django 3.0.6 on 2020-06-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_monitor', '0002_auto_20200601_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='url',
            field=models.URLField(max_length=1024),
        ),
    ]
