# Generated by Django 3.0.7 on 2020-06-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_monitor', '0003_auto_20200601_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='count',
            field=models.FloatField(default=0),
        ),
    ]
