# Generated by Django 3.0.6 on 2020-05-20 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_monitor', '0003_class_class_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detector',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('stream', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='class',
            name='detector_name',
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField()),
                ('class_id', models.CharField(max_length=32)),
                ('count', models.IntegerField(default=0)),
                ('detector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detector_log', to='traffic_monitor.Detector')),
                ('feed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_log', to='traffic_monitor.Feed')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='detector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='traffic_monitor.Detector'),
        ),
    ]
