# Generated by Django 3.1.1 on 2020-09-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_monitor', '0004_auto_20200821_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='charting_objects',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='monitor',
            name='charting_time_horizon',
            field=models.CharField(default='6', max_length=8),
        ),
        migrations.AddField(
            model_name='monitor',
            name='charting_time_zone',
            field=models.CharField(default='UTC', max_length=32),
            preserve_default=False,
        ),
    ]
