# Generated by Django 3.0.6 on 2020-05-21 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_monitor', '0004_auto_20200520_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='detector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='traffic_monitor.Detector'),
        ),
    ]
