# Generated by Django 3.0.6 on 2020-05-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_monitor', '0005_auto_20200521_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='stream',
            new_name='id',
        ),
        migrations.AddField(
            model_name='feed',
            name='url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
