# Generated by Django 3.1.1 on 2020-09-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_monitor', '0005_auto_20200910_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='class_colors',
            field=models.JSONField(default={}),
        ),
    ]
