# Generated by Django 3.0.6 on 2020-05-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_monitor', '0006_auto_20200521_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='key',
        ),
        migrations.AddField(
            model_name='log',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
