# Generated by Django 3.0.6 on 2020-05-21 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_monitor', '0007_auto_20200521_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='detector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detector_log', to='traffic_monitor.Detector'),
        ),
        migrations.AlterField(
            model_name='log',
            name='feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_log', to='traffic_monitor.Feed'),
        ),
    ]
