# Generated by Django 3.1.1 on 2020-09-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_monitor', '0007_auto_20200914_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='log_interval',
            field=models.IntegerField(default=60),
        ),
    ]
