# Generated by Django 3.1.1 on 2020-09-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_monitor', '0008_monitor_log_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='detector_sleep_throttle',
            field=models.IntegerField(default=60),
        ),
    ]
