# Generated by Django 3.0.6 on 2020-05-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_monitor', '0008_auto_20200521_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='id',
        ),
        migrations.AddField(
            model_name='log',
            name='key',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
