# Generated by Django 3.1.1 on 2020-09-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_monitor', '0009_monitor_detector_sleep_throttle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='detector_sleep_throttle',
            field=models.IntegerField(default=5),
        ),
    ]
