# Generated by Django 3.0.6 on 2020-05-21 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_monitor', '0009_auto_20200521_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='time_zone',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
    ]
