# Generated by Django 3.1.1 on 2020-09-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_monitor', '0010_auto_20200915_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='detector_confidence',
            field=models.FloatField(default=0.5),
        ),
    ]
