# Generated by Django 3.0.6 on 2020-05-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_monitor', '0011_auto_20200526_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detector',
            old_name='id',
            new_name='detector_id',
        ),
        migrations.RemoveField(
            model_name='class',
            name='detector',
        ),
        migrations.AddField(
            model_name='class',
            name='detector_id',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
