version: '3.1'

services:

  charting_service:
    build: .
    environment:
      NUM_PROCS: 4
      BOKEH_PORT: 8200
      APP_URL: 'host.docker.internal'
      APP_PORT: 8000
      FC_URL: 'host.docker.internal'
      FC_PORT: 8300
    ports:
      - "8200:8200"
