version: "3.1"

networks:
  default:
    external:
      name: infrastructure_default

services:

  web:
    build: .
    environment:
      - VERBOSITY=DEBUG
      - DB_NAME=monitor_db
      - DB_USER=monuser
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SECRET_KEY=sghkslbro5inb
    command: sh -c "python manage.py makemigrations; python manage.py migrate; python manage.py runserver 0.0.0.0:8200"
    volumes:
      - .:/code
    ports:
      - "8200:8200"
#    depends_on:
#      - db


