version: '3.1'

volumes:
  monitor_data:
    driver: local

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: monitor_db
      POSTGRES_USER: monuser
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - monitor_data:/var/lib/postgresql/data

#  web:
#    build: .
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/code
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db